### ISSUE TITLE
More logical matchers

### ISSUE THREAD

**Issue by povilasb** [ujh/hamcrest-rust#48]
Currently one has to to write to test boolean values: 
```
assert_that!(true, is(equal_to(true)));
assert_that!(false, is(equal_to(false)));
```
what do you think about having `is_true` and `is_false` matchers?:
```
assert_that!(true, is_true());
assert_that(false, if_false());
```

**Comment by ujh** [comment]
I thought about that as well as that's a use case I had a lot, too. Ideally I'd like to have it as 

``` rust
assert_that!(true, is(true))
```

I'm not entirely sure if/how that's possible but we could go with `is_true()` and `is_false()` in the mean time.

Unfortunately, I don't have the time to implement this right now, but I would welcome pull requests. 😁

**Comment by povilasb** [comment]
I'll give it a try once I have some spare time: might be two weeks from now :D
